apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-portfolio

spec:
  replicas: 5

  selector:
    matchLabels:
      app: devops-portfolio

  template:
    metadata:
      labels:
        app: devops-portfolio

    spec:
      containers:
        - name: devops-portfolio
          image: tejaltidake/tejal-devops-portfolio:V1
          ports:
            - containerPort: 80
